/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as Grade11RouteImport } from './routes/grade-11'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Grade12IndexRouteImport } from './routes/grade-12.index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as Grade12FieldRouteImport } from './routes/grade-12.$field'
import { Route as ExamSubjectIdRouteImport } from './routes/exam.$subjectId'
import { Route as Grade12FieldIndexRouteImport } from './routes/grade-12.$field.index'
import { Route as Grade12FieldSubjectRouteImport } from './routes/grade-12.$field.$subject'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Grade11Route = Grade11RouteImport.update({
  id: '/grade-11',
  path: '/grade-11',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Grade12IndexRoute = Grade12IndexRouteImport.update({
  id: '/grade-12/',
  path: '/grade-12/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const Grade12FieldRoute = Grade12FieldRouteImport.update({
  id: '/grade-12/$field',
  path: '/grade-12/$field',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSubjectIdRoute = ExamSubjectIdRouteImport.update({
  id: '/exam/$subjectId',
  path: '/exam/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const Grade12FieldIndexRoute = Grade12FieldIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Grade12FieldRoute,
} as any)
const Grade12FieldSubjectRoute = Grade12FieldSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => Grade12FieldRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/grade-11': typeof Grade11Route
  '/leaderboard': typeof LeaderboardRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/exam/$subjectId': typeof ExamSubjectIdRoute
  '/grade-12/$field': typeof Grade12FieldRouteWithChildren
  '/profile/$userId': typeof ProfileUserIdRoute
  '/grade-12/': typeof Grade12IndexRoute
  '/grade-12/$field/$subject': typeof Grade12FieldSubjectRoute
  '/grade-12/$field/': typeof Grade12FieldIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/grade-11': typeof Grade11Route
  '/leaderboard': typeof LeaderboardRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/exam/$subjectId': typeof ExamSubjectIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/grade-12': typeof Grade12IndexRoute
  '/grade-12/$field/$subject': typeof Grade12FieldSubjectRoute
  '/grade-12/$field': typeof Grade12FieldIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/grade-11': typeof Grade11Route
  '/leaderboard': typeof LeaderboardRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/exam/$subjectId': typeof ExamSubjectIdRoute
  '/grade-12/$field': typeof Grade12FieldRouteWithChildren
  '/profile/$userId': typeof ProfileUserIdRoute
  '/grade-12/': typeof Grade12IndexRoute
  '/grade-12/$field/$subject': typeof Grade12FieldSubjectRoute
  '/grade-12/$field/': typeof Grade12FieldIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/grade-11'
    | '/leaderboard'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/exam/$subjectId'
    | '/grade-12/$field'
    | '/profile/$userId'
    | '/grade-12/'
    | '/grade-12/$field/$subject'
    | '/grade-12/$field/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/grade-11'
    | '/leaderboard'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/exam/$subjectId'
    | '/profile/$userId'
    | '/grade-12'
    | '/grade-12/$field/$subject'
    | '/grade-12/$field'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/grade-11'
    | '/leaderboard'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/exam/$subjectId'
    | '/grade-12/$field'
    | '/profile/$userId'
    | '/grade-12/'
    | '/grade-12/$field/$subject'
    | '/grade-12/$field/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  Grade11Route: typeof Grade11Route
  LeaderboardRoute: typeof LeaderboardRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ExamSubjectIdRoute: typeof ExamSubjectIdRoute
  Grade12FieldRoute: typeof Grade12FieldRouteWithChildren
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  Grade12IndexRoute: typeof Grade12IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-11': {
      id: '/grade-11'
      path: '/grade-11'
      fullPath: '/grade-11'
      preLoaderRoute: typeof Grade11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-12/': {
      id: '/grade-12/'
      path: '/grade-12'
      fullPath: '/grade-12/'
      preLoaderRoute: typeof Grade12IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-12/$field': {
      id: '/grade-12/$field'
      path: '/grade-12/$field'
      fullPath: '/grade-12/$field'
      preLoaderRoute: typeof Grade12FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$subjectId': {
      id: '/exam/$subjectId'
      path: '/exam/$subjectId'
      fullPath: '/exam/$subjectId'
      preLoaderRoute: typeof ExamSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-12/$field/': {
      id: '/grade-12/$field/'
      path: '/'
      fullPath: '/grade-12/$field/'
      preLoaderRoute: typeof Grade12FieldIndexRouteImport
      parentRoute: typeof Grade12FieldRoute
    }
    '/grade-12/$field/$subject': {
      id: '/grade-12/$field/$subject'
      path: '/$subject'
      fullPath: '/grade-12/$field/$subject'
      preLoaderRoute: typeof Grade12FieldSubjectRouteImport
      parentRoute: typeof Grade12FieldRoute
    }
  }
}

interface Grade12FieldRouteChildren {
  Grade12FieldSubjectRoute: typeof Grade12FieldSubjectRoute
  Grade12FieldIndexRoute: typeof Grade12FieldIndexRoute
}

const Grade12FieldRouteChildren: Grade12FieldRouteChildren = {
  Grade12FieldSubjectRoute: Grade12FieldSubjectRoute,
  Grade12FieldIndexRoute: Grade12FieldIndexRoute,
}

const Grade12FieldRouteWithChildren = Grade12FieldRoute._addFileChildren(
  Grade12FieldRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  Grade11Route: Grade11Route,
  LeaderboardRoute: LeaderboardRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ExamSubjectIdRoute: ExamSubjectIdRoute,
  Grade12FieldRoute: Grade12FieldRouteWithChildren,
  ProfileUserIdRoute: ProfileUserIdRoute,
  Grade12IndexRoute: Grade12IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
